### ISSUE TITLE
Provide example apps 

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-coherence#35]
Would be great to have some example apps like we have here https://github.com/micronaut-projects/micronaut-oracle-cloud/tree/master/docs-examples where plp could just peek into working example. Also based on that we can extend launcher.

**Comment by aseovic** [comment]
We do have several examples:

1. https://github.com/coherence-community/todo-list-example/tree/master/java/micronaut-server (a simple To Do List application)
2. https://github.com/coherence-sockshop-micronaut (a full-blown eCommerce microservices demo)

Not sure what the best way is to surface those is. We were just going to announce them on our social media channels once we get the release out

**Comment by rlubke** [comment]
Per previous comment, we do have example applications that exist outside the project.  Closing this out.
